Repository deltaDAO/portal-euprogigant, pull requests merged in 2022-07, with the labels that each got.

#31 feat: add verified service provider name to asset details page
  src/components/atoms/Publisher/index.module.css
  src/components/atoms/Publisher/index.tsx
  src/components/atoms/VerifiedBadge.module.css
  src/components/atoms/VerifiedBadge.tsx
  src/components/atoms/VerifiedPublisher.tsx
  src/components/molecules/FormFields/URLInput/Input.tsx
  src/components/organisms/AssetContent/MetaMain.tsx
  src/providers/Asset.tsx
  src/utils/metadata.ts
Labels: Type: Enhancement

#34 Hotfix/compliance update
  app.config.js
Labels: Priority: High

#41 fix: asset details not showing for publisher
  src/components/organisms/AssetContent/index.tsx
Labels: Type: Bug
